name: java package

env:
  NAME: csye6225-webapp-zzy.zip
  AWS_REGION: us-east-1
  S3_BUCKET: codedeploy.zzyweb

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up java 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: package
        run: |
          zip -r ${{ env.NAME }} /home/runner/work/webapp/webapp/target/CSYE6225_zzy-0.0.1-SNAPSHOT.jar codedeploy/*.sh appspec.yml
          mkdir zzyweb
          mv ${{ env.NAME }} zzyweb/
          ls -al

      - name: config AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: copy artifact to s3
        run: |
          aws s3 sync ./zzyweb s3://${{ env.S3_BUCKET }}
