name: java package

env:
  NAME: csye6225-webapp-zzy.zip
  AWS_REGION: us-east-1
  S3_BUCKET: codedeploy.zzyweb
  APP_NAME: csye6225-webapp
  APP_DEPLOY_GROUP_NAME: csye6225-webapp-deployment

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2
      - name: set up java 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true

      - name: package
        run: |
          mv /home/runner/work/webapp/webapp/target/CSYE6225_zzy-0.0.1-SNAPSHOT.jar web.jar
          zip -r ${{ env.NAME }} web.jar codedeploy/*.sh appspec.yml
          mkdir zzyweb
          mv ${{ env.NAME }} zzyweb/
          ls -al

      - name: config AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: copy artifact to s3
        run: |
          aws s3 sync ./zzyweb s3://${{ env.S3_BUCKET }}


      - name: codedeploy API call
        run: |
          output=$(aws deploy create-deployment \
          --application-name ${{ env.APP_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.APP_DEPLOY_GROUP_NAME }} \
          --description "CSYE6225-code-deploy" \
          --s3-location bucket=${{ env.S3_BUCKET }},key=${{ env.NAME }},bundleType=zip \
          --region ${{ env.AWS_REGION }} \
          --output json)

          echo $output

          dID=$(echo $output | jq -r '.deploymentId')

          aws deploy wait deployment-successful --deployment-id $dID
